---
title: "Penguin Analysis Using Python"
author: "Margaret Lei"
date: 2026-09-28
execute:
  echo: true
  warning: false
---

## Analysis

First, let's load in the data about the Palmer Penguins; the first 6 rows are shown below.

```{python}
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()
```
\
How many islands do we have data for? Below, I count the unique names in the **island** column,
and then join them in a string.

```{python}
#| message: false
n_islands = penguins['island'].nunique()
islands = ", ".join(penguins['island'].unique())

print(f"{n_islands} islands: {islands}")
```
\
Let's find the average flipper length by species. Below, I group the data by the values in the **species** column,
and then calculate the average using the available flipper length measurements per species.

```{python}
#| label: avg_flip
#| fig-cap: "A table showing average flipper length in mm by species"

avg_flip = penguins.groupby(by='species').mean(numeric_only=True)[['flipper_length_mm']]
avg_flip
```
\
How about the average flipper length by species by island? I did the same thing as above,
but this time also grouping by island.

```{python}
#| fig-cap: "A table showing average flipper length in mm by species by island"
avg_flip_per_island = penguins.groupby(by=['species', 'island']).mean(numeric_only=True)[['flipper_length_mm']]
avg_flip_per_island
```
\
It seems Adelie penguins on the island of Torgersen have slightly longer mean flipper length. Neat!

## Credits

Data source:\
Horst AM, Hill AP, Gorman KB (2020). palmerpenguins: Palmer Archipelago (Antarctica) penguin data. 
R package version 0.1.0. https://allisonhorst.github.io/palmerpenguins/. doi: 10.5281/zenodo.3960218.

Data accessed via the palmerpenguins Python package and available by [CC-0](https://creativecommons.org/share-your-work/public-domain/cc0/) licence.